// cell-quality.workflow.js の driver harness(sc-jx8 B5)。
//
// cell-quality.workflow.js は Workflow tool 専用モジュール: `export const meta = {...}` の後、本体が
// top-level await + top-level `return result` で injected globals(agent/parallel/pipeline/log/phase/args/budget)
// を使う。標準 ESM/CJS として import すると export / top-level return / top-level await が SyntaxError になる
// =直接 import 不可。本 harness は Workflow tool の wrapping を再現する:
//   ファイルを読み → `export ` を剥がし → 本体を async 関数(new AsyncFunction)で包み → agent/log/phase 等の
//   stub を注入して実行し、return 値(result)を捕捉する(消失していた cell-quality-*-driver.mjs 群の方式・
//   doobidoo 9bf589cd)。new AsyncFunction 自体が本体を compile する=syntax が壊れていれば throw する
//   (= raw ファイルは node --check 不可だが、wrap 後の syntax 検証をここで担う。emit-wrapped モードは
//   その wrap 済みソースを stdout に出し、bats が node --check で二重に検証できるようにする)。
//
// 使い方:
//   node cell-quality-selftest.driver.mjs run          … CQ_ARGS(JSON) と CQ_* 環境変数で WF を stub 実行し
//                                                          結果を `K <key> <value>` 行で出力(bats が grep で assert)。
//   node cell-quality-selftest.driver.mjs emit-wrapped  … wrap 済みソースを stdout へ(node --check 用)。

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dir = dirname(fileURLToPath(import.meta.url))
const WF_PATH = resolve(__dir, '..', 'workflows', 'cell-quality.workflow.js')

// ── ソースを読み、Workflow wrapping を再現するための「本体」を得る ───────────────
// `export const meta` の `export ` だけを剥がす(meta 自体は本体内の const として残る)。他に export は無い。
function loadStrippedBody() {
  const raw = readFileSync(WF_PATH, 'utf8')
  if (!/^export\s+const\s+meta\b/m.test(raw)) {
    throw new Error('前提崩壊: `export const meta` が先頭に見当たらない(WF フォーマット変更?)')
  }
  // 先頭の `export const meta` を `const meta` に(1 箇所のみ・他 export は存在しない前提)。
  return raw.replace(/^export\s+const\s+meta\b/m, 'const meta')
}

const INJECTED = ['agent', 'parallel', 'pipeline', 'log', 'phase', 'args', 'budget', 'workflow']

// emit-wrapped: wrap 済みソースを標準の関数宣言として出力(node --check が parse できる valid ESM)。
function emitWrapped() {
  const body = loadStrippedBody()
  return `// AUTO-GENERATED by cell-quality-selftest.driver.mjs (emit-wrapped)。node --check 用。\n` +
    `async function __cqrun(${INJECTED.join(', ')}) {\n${body}\n}\n`
}

// ── Workflow の parallel/pipeline セマンティクスを忠実に再現 ─────────────────────
// parallel: barrier。thunk が throw したら null に正規化(reject は伝播しない)。
function makeParallel() {
  return (thunks) => Promise.all(thunks.map((t) => Promise.resolve().then(t).catch(() => null)))
}
// pipeline: 各 item を全 stage に通す(barrier 無し)。stage が throw したら item は null 化し以降 stage を skip。
// stage callback は (prevResult, originalItem, index)。stage1 の prevResult は item 自身。
function makePipeline() {
  return (items, ...stages) =>
    Promise.all(
      items.map(async (item, index) => {
        let cur = item
        for (let s = 0; s < stages.length; s++) {
          try {
            cur = await stages[s](cur, item, index)
          } catch (e) {
            return null
          }
        }
        return cur
      })
    )
}

// ── stub scenario を環境変数から読む ─────────────────────────────────────────────
const envBool = (name, dflt) => {
  const v = process.env[name]
  if (v === undefined || v === '') return dflt
  return v === 'true' || v === '1'
}
const envStr = (name, dflt) => {
  const v = process.env[name]
  return v === undefined || v === '' ? dflt : v
}

async function runWorkflow() {
  // CQ_ARGS_STRING が設定されていれば「そのままの string」を args として渡す(WF の defensive parse 経路を踏む)。
  // 通常は CQ_ARGS(JSON)を object にして渡す。
  const wfArgs = process.env.CQ_ARGS_STRING !== undefined ? process.env.CQ_ARGS_STRING : JSON.parse(process.env.CQ_ARGS || '{}')

  const CLASSIFY_TYPE = envStr('CQ_CLASSIFY_TYPE', typeof wfArgs.taskType === 'string' && wfArgs.taskType ? wfArgs.taskType : 'testable')
  const BASELINE_RAN = envBool('CQ_BASELINE_RAN', true)
  const BASELINE_PASSED = envBool('CQ_BASELINE_PASSED', true)
  const FINAL_PASSED = envBool('CQ_FINAL_PASSED', true)
  const SELFTEST_AGENT_FAIL = envStr('CQ_SELFTEST_AGENT_FAIL', '') // 'baseline' | 'final' | ''
  const REVIEW_FINDINGS = JSON.parse(process.env.CQ_REVIEW_FINDINGS || '[]')
  const VERIFY_REFUTED = envBool('CQ_VERIFY_REFUTED', true) // 既定=refute(clean)。confirmed にするには false
  const FIX_SELFTEST_PASSED = envBool('CQ_FIX_SELFTEST_PASSED', true)
  // (sc-j32 errata) autofix stub の summary を差し替える knob。既定 'stub autofix'(非 placeholder)。
  // placeholder('test' 等)を注入すると degFix が発火し、fix 段の degenerate 配線(schemaAgent(agent,…,degFix))を
  // end-to-end で駆動できる=発端事例(fix summary="test" の最終値化)の回帰ガードに使う。
  const FIX_SUMMARY = envStr('CQ_FIX_SUMMARY', 'stub autofix')
  const SNAPSHOT = envStr('CQ_SNAPSHOT', 'diff --git a/x b/x\n@@ -1 +1 @@\n-old\n+new\n')

  const calls = [] // agent 呼び出しの label を順に記録(ordering/回数の assert 用)
  const logs = []
  const agentTypeCalls = [] // (sc-xyw) agentType が付いた呼出しの記録({label, agentType})=降格の後続伝播を検証する
  const effortCalls = [] // (sc-dc9) 各 agent 呼出しの opts.effort を記録({label, effort})=全 agent に effort が pin されたか検証する
  const promptCalls = [] // (sc-xyw errata) 各呼出しの prompt に RO_DISCIPLINE 前置が付いたかを記録({label, hasDiscipline})=降格後の read-only 規律代替(中核安全機構)を behavioral に検証する
  const RO_NOTFOUND = envBool('CQ_RO_NOTFOUND', false) // (sc-xyw) true=agentType 付き呼出しを probe 形状 not found で reject し roAgent fallback を発火させる

  const agentStub = (prompt, opts) => {
    const label = (opts && opts.label) || ''
    const agentType = opts && opts.agentType
    calls.push(label)
    if (agentType) agentTypeCalls.push({ label, agentType })
    effortCalls.push({ label, effort: opts && opts.effort }) // (sc-dc9) opts.effort を記録(roAgent/runAgent は opts を透過ゆえ届く)
    // (sc-xyw errata) roAgent fallback は降格後 `prompt + RO_DISCIPLINE` を渡し agentType 構造強制を prompt 規律で代替する。
    // この前置マーカー(agentType 構造強制の代替)が付いた呼出しを記録し、消失(=完全 fail-open 退行)を behavioral に検出する。
    promptCalls.push({ label, hasDiscipline: /agentType 構造強制の代替/.test(String(prompt == null ? '' : prompt)) })
    // (sc-xyw) fallback シナリオ: agentType 付き呼出しは probe verified の "not found" 形状で reject する。
    // roAgent は isAgentTypeNotFound を検知 → [RO-FALLBACK] を log → 降格 flag を立て → agentType 無しで再呼出しする
    // (=再呼出しは agentType 無しゆえここを通らず resolve)。降格が後続へ伝播していれば以降の read-only 段も最初から
    // agentType 無しで呼ばれる=agentType 付き呼出しは初回の 1 回のみ。伝播が壊れていれば毎段 reject→再呼出しが起き
    // agentType 付き呼出しと [RO-FALLBACK] log が複数になる(=退行を behavioral に検出できる)。'none' は fallback 済相当ゆえ除外。
    if (RO_NOTFOUND && agentType && agentType !== 'none') {
      return Promise.reject(
        new Error(`agent(${agentType}): agent type '${agentType}' not found. Available agents: claude, general-purpose, Plan, statusline-setup`)
      )
    }
    if (label.startsWith('classify')) return Promise.resolve({ taskType: CLASSIFY_TYPE, rationale: 'stub' })
    if (label.startsWith('selftest:baseline')) {
      if (SELFTEST_AGENT_FAIL === 'baseline') return Promise.reject(new Error('stub baseline runner throw'))
      return Promise.resolve({ ran: BASELINE_RAN, passed: BASELINE_PASSED, exitCode: BASELINE_PASSED ? 0 : 1, rawLog: 'STUB_BASELINE_LOG: selftest output line' })
    }
    if (label.startsWith('selftest:final')) {
      if (SELFTEST_AGENT_FAIL === 'final') return Promise.reject(new Error('stub final runner throw'))
      return Promise.resolve({ ran: true, passed: FINAL_PASSED, exitCode: FINAL_PASSED ? 0 : 1, rawLog: 'STUB_FINAL_LOG: selftest output line' })
    }
    if (label.startsWith('plan')) return Promise.resolve({ acceptance: 'stub acceptance', notes: '' })
    if (label.startsWith('implement')) return Promise.resolve('stub implement done')
    if (label.startsWith('snapshot')) return Promise.resolve(SNAPSHOT)
    if (label.startsWith('review:')) return Promise.resolve({ findings: REVIEW_FINDINGS })
    if (label.startsWith('verify:')) return Promise.resolve({ refuted: VERIFY_REFUTED, confidence: 'high', reasoning: 'stub' })
    if (label.startsWith('autofix')) {
      return Promise.resolve({ applied: ['stub fix'], selfTestRan: true, selfTestPassed: FIX_SELFTEST_PASSED, amended: FIX_SELFTEST_PASSED, summary: FIX_SUMMARY, newDiff: SNAPSHOT })
    }
    return Promise.resolve(null)
  }

  const stubs = {
    agent: agentStub,
    parallel: makeParallel(),
    pipeline: makePipeline(),
    log: (m) => logs.push(String(m)),
    phase: () => {},
    args: wfArgs,
    budget: { total: null, spent: () => 0, remaining: () => Infinity },
    workflow: async () => null,
  }

  const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor
  const body = loadStrippedBody()
  // new AsyncFunction が body を compile する=syntax 不正なら here で throw(wrap 後の syntax 検証)。
  const run = new AsyncFunction(...INJECTED, body)
  const result = await run(...INJECTED.map((k) => stubs[k]))

  return { result, calls, logs, agentTypeCalls, promptCalls, effortCalls }
}

// ── 出力: `K <key> <value>` 行(bats が grep で assert)+ 生 JSON ─────────────────
function firstIndex(calls, prefix) {
  for (let i = 0; i < calls.length; i++) if (calls[i].startsWith(prefix)) return i
  return -1
}

function printResult(result, calls, logs, agentTypeCalls, promptCalls, effortCalls) {
  const K = (k, v) => console.log(`K ${k} ${v}`)
  const b = result.selfTestBaseline || {}
  const f = result.selfTestFinal || {}
  K('selfTestBaseline.present', result.selfTestBaseline !== undefined)
  K('selfTestBaseline.ran', b.ran)
  K('selfTestBaseline.skipped', b.skipped === true)
  K('selfTestBaseline.passed', b.passed)
  K('selfTestBaseline.hasRawLog', typeof b.rawLog === 'string' && b.rawLog.length > 0)
  K('selfTestBaseline.rawLog_len', typeof b.rawLog === 'string' ? b.rawLog.length : -1)
  K('selfTestBaseline.error', b.error === true)
  K('selfTestFinal.present', result.selfTestFinal !== undefined)
  K('selfTestFinal.ran', f.ran)
  K('selfTestFinal.skipped', f.skipped === true)
  K('selfTestFinal.passed', f.passed)
  K('selfTestFinal.hasRawLog', typeof f.rawLog === 'string' && f.rawLog.length > 0)
  K('selfTestFinal.error', f.error === true)
  K('converged', result.converged === true)
  K('escalate', result.escalate === true)
  K('autoFix', result.autoFix === true)
  K('taskType', result.taskType)
  K('rounds', result.rounds)
  const selftestCalls = calls.filter((c) => c.startsWith('selftest:')).length
  K('selftestAgentCalls', selftestCalls)
  const bi = firstIndex(calls, 'selftest:baseline')
  const fi = firstIndex(calls, 'selftest:final')
  K('baselineBeforeFinal', bi >= 0 && fi >= 0 ? bi < fi : 'na')
  // baseline は implement/review より前(実装前=regression 起点)であることも順序で確認。
  const impl = firstIndex(calls, 'implement')
  const rev = firstIndex(calls, 'review:')
  K('baselineBeforeReview', bi >= 0 && rev >= 0 ? bi < rev : 'na')
  K('baselineBeforeImplement', bi >= 0 && impl >= 0 ? bi < impl : 'na')
  // gate は空白を含むので substring 判定用に prefix だけ出す。
  const gate = String(result.gate || '')
  K('gatePrefix', gate.split(':')[0])
  // (sc-xyw) roAgent fallback の監査軸。
  // roFallbackActive: 全 return 経路で返り値に載る最終降格状態(acceptance 3)。
  // roFallbackLogCount: [RO-FALLBACK] loud log の回数(fallback シナリオでちょうど 1=降格が後続伝播した証拠)。
  // agentTypeCallCount: agentType 付きで呼ばれた総数(fallback シナリオで 1=初回のみ agentType 付き→以降降格伝播で 0)。
  // reviewVerifyCalls: review:/verify: 段が実際に走った数(fallback 後も review/verify 経路が生きている証拠)。
  K('roFallbackActive', result.roFallbackActive === true)
  const roFbLogCount = (logs || []).filter((l) => String(l).includes('[RO-FALLBACK]')).length
  K('roFallbackLogCount', roFbLogCount)
  K('agentTypeCallCount', (agentTypeCalls || []).length)
  // (sc-xyw errata) roDisciplineCallCount: prompt に RO_DISCIPLINE 前置マーカーが付いた呼出しの総数。
  // fallback シナリオで >0(降格後の read-only 段が read-only 規律を prompt で代替)・正常時で 0(前置しない)。
  // この前置が消えても従来の log/agentType 系 assert は全 green ゆえ、silent fail-open 退行を捕える専用軸。
  const roDisciplineCallCount = (promptCalls || []).filter((p) => p && p.hasDiscipline).length
  K('roDisciplineCallCount', roDisciplineCallCount)
  const rvCalls = calls.filter((c) => c.startsWith('review:') || c.startsWith('verify:')).length
  K('reviewVerifyCalls', rvCalls)
  // (sc-dc9) effort pin の behavioral 検証: 全 agent 呼出しに opts.effort が届いたか + その distinct 値。
  // effortAgentCalls: effort を記録した呼出し総数(= 全 agent 呼出し)。
  // effortAllPinned: すべての agent 呼出しで effort が defined(undefined が 1 つも無い=全箇所 pin の証拠)。
  // effortDistinct: 実際に届いた effort の distinct 値(既定なら 'high' のみ・args.effort 指定ならその値)。
  const ec = effortCalls || []
  K('effortAgentCalls', ec.length)
  K('effortAllPinned', ec.length > 0 && ec.every((e) => e && e.effort !== undefined))
  K('effortDistinct', Array.from(new Set(ec.map((e) => String(e && e.effort)))).sort().join(','))
  // (sc-94z) per-stage effort の behavioral 検証: 各段の agent 呼出しに届いた opts.effort を label prefix 別に読む。
  // guard 段(review/verify/fix)が cell effort の一括下げから独立に high を保つか等を段ごとに pin する。
  // 該当段が走らなかった run(clean review で fix なし・doPlan/doImplement 無しで plan/implement なし)は '<none>'。
  const effortOf = (prefix) => {
    const hit = ec.find((e) => e && typeof e.label === 'string' && e.label.startsWith(prefix))
    return hit ? String(hit.effort) : '<none>'
  }
  K('effortStage.classify', effortOf('classify'))
  K('effortStage.selftest', effortOf('selftest:'))
  K('effortStage.snapshot', effortOf('snapshot'))
  K('effortStage.plan', effortOf('plan'))
  K('effortStage.implement', effortOf('implement'))
  K('effortStage.review', effortOf('review:'))
  K('effortStage.verify', effortOf('verify:'))
  K('effortStage.fix', effortOf('autofix'))
  // (sc-94z) result.effort は per-stage 要約 object へ変わった(旧: 単一 string)。各フィールドを個別に出す。
  const re = result.effort && typeof result.effort === 'object' ? result.effort : {}
  K('resultEffort.cell', re.cell)
  K('resultEffort.review', re.review)
  K('resultEffort.verify', re.verify)
  K('resultEffort.fix', re.fix)
  K('resultEffort.classify', re.classify)
  K('resultEffort.selfTest', re.selfTest)
  K('resultEffort.snapshot', re.snapshot)
  // (sc-dc9) allowlist 外 args.effort → 既定 high へ fail-safe した際、warn log が実際に発火したか(behavioral)。
  // logs は既定では stdout に dump しないため、この behavioral K 行で fail-safe の可視化(silent に倒さない)を検証する。
  K('effortFailSafeWarned', (logs || []).some((l) => String(l).includes('許可外')))
  // (sc-2wv) guard 段 knob(reviewEffort/verifyEffort)を floor(high)未満で渡した際、WF が fail-safe で high へ
  // 引き上げ warn したか(behavioral)。floor-clamp は '許可外'(allowlist 外)とは別経路(allowlist 内だが下げ拒否)
  // ゆえ専用マーカー '下限フロア' で弁別する。これが消える(silent に下げる)退行を behavioral に捕える。
  K('effortFloorClamped', (logs || []).some((l) => String(l).includes('下限フロア')))
  console.log(`ESCALATE_REASON ${String(result.escalateReason || '')}`)
  console.log(`RESULT ${JSON.stringify(result)}`)
}

// ── entrypoint ───────────────────────────────────────────────────────────────
const mode = process.argv[2] || 'run'
if (mode === 'emit-wrapped') {
  process.stdout.write(emitWrapped())
} else if (mode === 'run') {
  runWorkflow()
    .then(({ result, calls, logs, agentTypeCalls, promptCalls, effortCalls }) => {
      printResult(result, calls, logs, agentTypeCalls, promptCalls, effortCalls)
    })
    .catch((e) => {
      console.error(`DRIVER_ERROR: ${e && e.stack ? e.stack : e}`)
      process.exit(1)
    })
} else {
  console.error(`unknown mode: ${mode}`)
  process.exit(2)
}
