// cell-quality.workflow.js の driver harness(sc-jx8 B5)。
//
// cell-quality.workflow.js は Workflow tool 専用モジュール: `export const meta = {...}` の後、本体が
// top-level await + top-level `return result` で injected globals(agent/parallel/pipeline/log/phase/args/budget)
// を使う。標準 ESM/CJS として import すると export / top-level return / top-level await が SyntaxError になる
// =直接 import 不可。本 harness は Workflow tool の wrapping を再現する:
//   ファイルを読み → `export ` を剥がし → 本体を async 関数(new AsyncFunction)で包み → agent/log/phase 等の
//   stub を注入して実行し、return 値(result)を捕捉する(消失していた cell-quality-*-driver.mjs 群の方式・
//   doobidoo 9bf589cd)。new AsyncFunction 自体が本体を compile する=syntax が壊れていれば throw する
//   (= raw ファイルは node --check 不可だが、wrap 後の syntax 検証をここで担う。emit-wrapped モードは
//   その wrap 済みソースを stdout に出し、bats が node --check で二重に検証できるようにする)。
//
// 使い方:
//   node cell-quality-selftest.driver.mjs run          … CQ_ARGS(JSON) と CQ_* 環境変数で WF を stub 実行し
//                                                          結果を `K <key> <value>` 行で出力(bats が grep で assert)。
//   node cell-quality-selftest.driver.mjs emit-wrapped  … wrap 済みソースを stdout へ(node --check 用)。

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dir = dirname(fileURLToPath(import.meta.url))
const WF_PATH = resolve(__dir, '..', 'workflows', 'cell-quality.workflow.js')

// ── ソースを読み、Workflow wrapping を再現するための「本体」を得る ───────────────
// `export const meta` の `export ` だけを剥がす(meta 自体は本体内の const として残る)。他に export は無い。
function loadStrippedBody() {
  const raw = readFileSync(WF_PATH, 'utf8')
  if (!/^export\s+const\s+meta\b/m.test(raw)) {
    throw new Error('前提崩壊: `export const meta` が先頭に見当たらない(WF フォーマット変更?)')
  }
  // 先頭の `export const meta` を `const meta` に(1 箇所のみ・他 export は存在しない前提)。
  return raw.replace(/^export\s+const\s+meta\b/m, 'const meta')
}

const INJECTED = ['agent', 'parallel', 'pipeline', 'log', 'phase', 'args', 'budget', 'workflow']

// emit-wrapped: wrap 済みソースを標準の関数宣言として出力(node --check が parse できる valid ESM)。
function emitWrapped() {
  const body = loadStrippedBody()
  return `// AUTO-GENERATED by cell-quality-selftest.driver.mjs (emit-wrapped)。node --check 用。\n` +
    `async function __cqrun(${INJECTED.join(', ')}) {\n${body}\n}\n`
}

// ── (sc-k33c) cap 系例外の stub 生成: name 経路と message 経路を **排他的に** 作り分ける ────────────
// WF 側の判定は「name **または** message の指紋」(AND 禁止)。AND に退行すると片方だけでは検知できなくなる
// ため、mode='name' は message に指紋を一切含めず / mode='message' は name を既定の 'Error' のまま にする。
// kind: 'quota'(turn token budget 枯渇) | 'error'(harness の agent 本数上限) | 'plain'(cap ではない例外)。
// (sc-k33c errata) 'plain' = name にも message にも cap 指紋を **一切** 含まない machinery 例外。capCatch の
// fail-closed 再 throw(`if (!reason) throw e`)を behavioral に駆動できる唯一の経路。これが無いと「6 つの新
// call site が非 cap 例外まで飲み込む完全 fail-open」への退行に検知面が無い(CQ_THROW_KIND の 'quota'/'error'
// は両方 makeCapError＝常に cap 指紋を持つため、fail-closed 分岐を一度も踏めなかった)。
const CAP_ERR_MODE = process.env.CQ_CAP_ERR_MODE || 'name'
function makeCapError(kind) {
  if (kind === 'plain') {
    // 指紋('budget exceeded'/'token budget'/'agent cap'/'agent limit'/'exceeded the agent')を含まない文言。
    return new Error('stub machinery failure: deliberately fingerprint-free (not a cap condition)')
  }
  // (sc-k33c ERRATA-01 B2) near-miss: 指紋の **語の途中に一致してしまう** 実在しうる machinery 文言。
  // 素の substring 一致だと cap と誤判定され fail-closed 再 throw が迂回される(gate 実測の退行形)。
  // 語境界一致なら非 cap のままであることを negative tooth で固定する。CQ_THROW_KIND で選ぶ。
  if (kind === 'near-capability') return new Error('agent capability probe returned malformed payload')
  if (kind === 'near-capacity') return new Error('agent capacity planner returned no route')
  if (kind === 'near-exceededness') return new Error('budget exceededness metric unavailable')
  if (kind === 'near-limitless') return new Error('agent limitless mode is not supported here')
  if (CAP_ERR_MODE === 'message') {
    // name は 'Error' のまま = message 指紋だけで cap と判定できるか(OR の右辺)を駆動する。
    return new Error(kind === 'quota' ? 'workflow token budget exhausted for this turn' : 'workflow agent cap reached')
  }
  // message には指紋を一切含めない = name だけで cap と判定できるか(OR の左辺)を駆動する。
  const e = new Error('stub throw (no fingerprint in this message)')
  e.name = kind === 'quota' ? 'WorkflowBudgetExceededError' : 'WorkflowAgentCapError'
  return e
}
// (sc-k33c K1b(iv)) CQ_THROW_AT_STAGE: 'pipeline' / 'parallel' = 入口の【同期 throw】を再現する
// (harness の reject 形より厳しい形で WF の try/catch 包みを駆動する)。'element-budget' = 要素側(verify agent)
// が budget 例外を投げる形 = parallel が要素を null 化する経路の再現。
const THROW_AT_STAGE = process.env.CQ_THROW_AT_STAGE || ''

// ── Workflow の parallel/pipeline セマンティクスを忠実に再現 ─────────────────────
// parallel: barrier。thunk が throw したら null に正規化(reject は伝播しない)。
function makeParallel() {
  return (thunks) => {
    if (THROW_AT_STAGE === 'parallel') throw makeCapError('quota')
    return Promise.all(thunks.map((t) => Promise.resolve().then(t).catch(() => null)))
  }
}
// pipeline: 各 item を全 stage に通す(barrier 無し)。stage が throw したら item は null 化し以降 stage を skip。
// stage callback は (prevResult, originalItem, index)。stage1 の prevResult は item 自身。
function makePipeline() {
  return (items, ...stages) => {
    if (THROW_AT_STAGE === 'pipeline') throw makeCapError('error')
    return Promise.all(
      items.map(async (item, index) => {
        let cur = item
        for (let s = 0; s < stages.length; s++) {
          try {
            cur = await stages[s](cur, item, index)
          } catch (e) {
            return null
          }
        }
        return cur
      })
    )
  }
}

// ── stub scenario を環境変数から読む ─────────────────────────────────────────────
const envBool = (name, dflt) => {
  const v = process.env[name]
  if (v === undefined || v === '') return dflt
  return v === 'true' || v === '1'
}
const envStr = (name, dflt) => {
  const v = process.env[name]
  return v === undefined || v === '' ? dflt : v
}

// (sc-pfn4) throw 経路の観測面: WF が args fail-fast で throw すると runWorkflow はローカルの calls/logs を
// 返せず「agent が 1 体も起動していない」を外から確認できなかった。集計器を外側スコープへ持ち上げ、
// 成功経路は従来どおり(この object を経由するだけ・stdout は byte 同一)・throw 経路では entrypoint の
// .catch が同じ集計器から DRIVER_AGENT_CALLS / DRIVER_CALLSEQ を stderr へ出す。
const collected = { calls: [], logs: [], agentTypeCalls: [], promptCalls: [], effortCalls: [] }

async function runWorkflow() {
  // CQ_ARGS_STRING が設定されていれば「そのままの string」を args として渡す(WF の defensive parse 経路を踏む)。
  // 通常は CQ_ARGS(JSON)を object にして渡す。
  const wfArgs = process.env.CQ_ARGS_STRING !== undefined ? process.env.CQ_ARGS_STRING : JSON.parse(process.env.CQ_ARGS || '{}')

  const CLASSIFY_TYPE = envStr('CQ_CLASSIFY_TYPE', typeof wfArgs.taskType === 'string' && wfArgs.taskType ? wfArgs.taskType : 'testable')
  const BASELINE_RAN = envBool('CQ_BASELINE_RAN', true)
  const BASELINE_PASSED = envBool('CQ_BASELINE_PASSED', true)
  const FINAL_PASSED = envBool('CQ_FINAL_PASSED', true)
  const SELFTEST_AGENT_FAIL = envStr('CQ_SELFTEST_AGENT_FAIL', '') // 'baseline' | 'final' | ''
  const REVIEW_FINDINGS = JSON.parse(process.env.CQ_REVIEW_FINDINGS || '[]')
  const VERIFY_REFUTED = envBool('CQ_VERIFY_REFUTED', true) // 既定=refute(clean)。confirmed にするには false
  const FIX_SELFTEST_PASSED = envBool('CQ_FIX_SELFTEST_PASSED', true)
  // (sc-j32 errata) autofix stub の summary を差し替える knob。既定 'stub autofix'(非 placeholder)。
  // placeholder('test' 等)を注入すると degFix が発火し、fix 段の degenerate 配線(schemaAgent(agent,…,degFix))を
  // end-to-end で駆動できる=発端事例(fix summary="test" の最終値化)の回帰ガードに使う。
  const FIX_SUMMARY = envStr('CQ_FIX_SUMMARY', 'stub autofix')
  const SNAPSHOT = envStr('CQ_SNAPSHOT', 'diff --git a/x b/x\n@@ -1 +1 @@\n-old\n+new\n')

  // (sc-pfn4) 実体は外側スコープの collected(throw 経路でも読めるようにするため)。以降の使い方・意味は不変。
  const calls = collected.calls // agent 呼び出しの label を順に記録(ordering/回数の assert 用)
  const logs = collected.logs
  const agentTypeCalls = collected.agentTypeCalls // (sc-xyw) agentType が付いた呼出しの記録({label, agentType})=降格の後続伝播を検証する
  const effortCalls = collected.effortCalls // (sc-dc9) 各 agent 呼出しの opts.effort を記録({label, effort})=全 agent に effort が pin されたか検証する
  const promptCalls = collected.promptCalls // (sc-xyw errata) 各呼出しの prompt に RO_DISCIPLINE 前置が付いたかを記録({label, hasDiscipline})=降格後の read-only 規律代替(中核安全機構)を behavioral に検証する
  const RO_NOTFOUND = envBool('CQ_RO_NOTFOUND', false) // (sc-xyw) true=agentType 付き呼出しを probe 形状 not found で reject し roAgent fallback を発火させる
  // (sc-k33c) cap の決定論 knob。既定はすべて「無効(=現状維持)」= 既存 bats は 1 本も影響を受けない。
  const BUDGET_THROW_AT = Number(process.env.CQ_BUDGET_THROW_AT || 0) // N 本目の agent で quota 例外
  const AGENT_CAP_AT = Number(process.env.CQ_AGENT_CAP || 0) // N 本目の agent で agent-cap 例外
  const SPEND_PER_AGENT = Number(process.env.CQ_SPEND_PER_AGENT || 0) // budget.spent() の 1 本あたり増分(token 情報ログ用)
  const BUDGET_TOTAL = process.env.CQ_BUDGET_TOTAL ? Number(process.env.CQ_BUDGET_TOTAL) : null // budget.total(null=未設定)
  const THROW_AT_LABEL = envStr('CQ_THROW_AT_LABEL', '') // label prefix 指定で cap 例外を投げる
  const THROW_KIND = envStr('CQ_THROW_KIND', 'quota') // 'quota' | 'error' | 'plain'(=cap 指紋なし=fail-closed 駆動)
  const REVIEW_ORDER = envStr('CQ_REVIEW_ORDER', '') // 'reverse' = review の解決順を反転(K1c 決定論の駆動)
  let reviewSeq = 0
  // (sc-pyab 項目4) round 別 stub knob。round ごとに review findings / verify verdict を差し替える。
  // 既存 knob(CQ_REVIEW_FINDINGS / CQ_VERIFY_REFUTED)は「全 round 同一」しか表現できず、round 3 で初めて
  // クリーンになる run(= 系統A の正方向 tooth)も、round 間で主張集合が変わる run も駆動できなかった。
  //   CQ_REVIEW_FINDINGS_BY_ROUND='{"1":[...],"3":[]}'  … round→findings(未指定 round は CQ_REVIEW_FINDINGS)
  //   CQ_VERIFY_REFUTED_BY_ROUND='{"3":true}'            … round→refuted (未指定 round は CQ_VERIFY_REFUTED)
  // 【既定不変が load-bearing】未設定(null)なら参照すらせず既存値へ倒すので挙動は byte 単位で従来と同一。
  // 壊れる先を正確に言うと: cap.bats の base 木対照(materialize_base_tree)は **HEAD の driver を base 木へ
  // cp する**ので、driver 既定の変更は base 側と HEAD 側へ **等しく** 効き、callSeq / agentCallTotal の
  // 現物対現物比較は既定変更に **不感**である(= 「既定を変えると base 対照が false RED になる」という因果は
  // 成立しない・実測)。実際に割れるのは (a) literal 期待値を持つ tooth(cell-quality-cap.bats の
  // `verifyCallCount -eq 8/12` `agentCallTotal -eq 8` 等)と、(b) **knob 導入前の driver** を対照に取る
  // loop.bats の「driver knob 既定不変」tooth(L-C1)。既定を動かさない結論は変わらないが、根拠をこの 2 点に置く。
  //   CQ_THROW_AT_ROUND='3'                              … CQ_THROW_AT_LABEL の注入を **その round に限定**
  //     (未設定 = 全 round= 従来どおり)。verify 段が **特定 round だけ**落ちた run(= verdict:null → unverified
  //     行きで confirmed が 0 になる run)を駆動する唯一の経路。label 前方一致だけでは round を切れない
  //     (WF が焼く round 番号は label の **末尾**にある)。
  const REVIEW_FINDINGS_BY_ROUND = JSON.parse(process.env.CQ_REVIEW_FINDINGS_BY_ROUND || 'null')
  const VERIFY_REFUTED_BY_ROUND = JSON.parse(process.env.CQ_VERIFY_REFUTED_BY_ROUND || 'null')
  const THROW_AT_ROUND = envStr('CQ_THROW_AT_ROUND', '')
  // label 末尾の ' r<N>'(WF が焼く round 番号)から round を読む。読めなければ '' = 既定へ倒す(fail-safe)。
  const roundOf = (label) => {
    const m = /\br(\d+)$/.exec(String(label || ''))
    return m ? m[1] : ''
  }
  const byRound = (map, label, dflt) => {
    const r = roundOf(label)
    return map && r && Object.prototype.hasOwnProperty.call(map, r) ? map[r] : dflt
  }

  const agentStub = (prompt, opts) => {
    const label = (opts && opts.label) || ''
    const agentType = opts && opts.agentType
    calls.push(label)
    if (agentType) agentTypeCalls.push({ label, agentType })
    effortCalls.push({ label, effort: opts && opts.effort }) // (sc-dc9) opts.effort を記録(roAgent/runAgent は opts を透過ゆえ届く)
    // (sc-xyw errata) roAgent fallback は降格後 `prompt + RO_DISCIPLINE` を渡し agentType 構造強制を prompt 規律で代替する。
    // この前置マーカー(agentType 構造強制の代替)が付いた呼出しを記録し、消失(=完全 fail-open 退行)を behavioral に検出する。
    // (sc-mbcm) prompt 全文も保持する=CQ_PROMPT_GREP 軸(contextFile 注入等 prompt-level 配線の behavioral 検証)が読む。
    promptCalls.push({ label, hasDiscipline: /agentType 構造強制の代替/.test(String(prompt == null ? '' : prompt)), prompt: String(prompt == null ? '' : prompt) })
    // (sc-k33c) cap 系例外の注入: N 本目の agent 呼出しで budget/agent-cap 例外を投げる(1-indexed)。
    // 層3(cap 系例外 → capExceeded 正規化)を stub で end-to-end 駆動する唯一の経路(実機の turn token budget は
    // 呼出元が設定しないと発火しないため=K9 の「層3 は stub 検証のみ」)。
    // CQ_THROW_AT_LABEL: label prefix 指定で cap 例外を投げる(呼出し番号を数えずに 6 call site を個別に狙える
    // = 変異注入 tooth が call 順の変化に脆くならない)。kind は CQ_THROW_KIND('quota'|'error')。
    // (sc-pyab) CQ_THROW_AT_ROUND 未設定なら短絡して従来と同一(既定不変)。設定時のみ round を突き合わせる。
    if (THROW_AT_LABEL && label.startsWith(THROW_AT_LABEL) && (!THROW_AT_ROUND || roundOf(label) === THROW_AT_ROUND))
      return Promise.reject(makeCapError(THROW_KIND))
    if (BUDGET_THROW_AT > 0 && calls.length === BUDGET_THROW_AT) return Promise.reject(makeCapError('quota'))
    if (AGENT_CAP_AT > 0 && calls.length === AGENT_CAP_AT) return Promise.reject(makeCapError('error'))
    if (THROW_AT_STAGE === 'element-budget' && label.startsWith('verify:')) return Promise.reject(makeCapError('quota'))
    // (sc-xyw) fallback シナリオ: agentType 付き呼出しは probe verified の "not found" 形状で reject する。
    // roAgent は isAgentTypeNotFound を検知 → [RO-FALLBACK] を log → 降格 flag を立て → agentType 無しで再呼出しする
    // (=再呼出しは agentType 無しゆえここを通らず resolve)。降格が後続へ伝播していれば以降の read-only 段も最初から
    // agentType 無しで呼ばれる=agentType 付き呼出しは初回の 1 回のみ。伝播が壊れていれば毎段 reject→再呼出しが起き
    // agentType 付き呼出しと [RO-FALLBACK] log が複数になる(=退行を behavioral に検出できる)。'none' は fallback 済相当ゆえ除外。
    if (RO_NOTFOUND && agentType && agentType !== 'none') {
      return Promise.reject(
        new Error(`agent(${agentType}): agent type '${agentType}' not found. Available agents: claude, general-purpose, Plan, statusline-setup`)
      )
    }
    if (label.startsWith('classify')) return Promise.resolve({ taskType: CLASSIFY_TYPE, rationale: 'stub' })
    if (label.startsWith('selftest:baseline')) {
      if (SELFTEST_AGENT_FAIL === 'baseline') return Promise.reject(new Error('stub baseline runner throw'))
      return Promise.resolve({ ran: BASELINE_RAN, passed: BASELINE_PASSED, exitCode: BASELINE_PASSED ? 0 : 1, rawLog: 'STUB_BASELINE_LOG: selftest output line' })
    }
    if (label.startsWith('selftest:final')) {
      if (SELFTEST_AGENT_FAIL === 'final') return Promise.reject(new Error('stub final runner throw'))
      return Promise.resolve({ ran: true, passed: FINAL_PASSED, exitCode: FINAL_PASSED ? 0 : 1, rawLog: 'STUB_FINAL_LOG: selftest output line' })
    }
    if (label.startsWith('plan')) return Promise.resolve({ acceptance: 'stub acceptance', notes: '' })
    if (label.startsWith('implement')) return Promise.resolve('stub implement done')
    if (label.startsWith('snapshot')) return Promise.resolve(SNAPSHOT)
    if (label.startsWith('review:')) {
      const res = { findings: byRound(REVIEW_FINDINGS_BY_ROUND, label, REVIEW_FINDINGS) }
      // (sc-k33c K1c) stage1(review)の解決順を反転させる knob。pipeline は barrier 無しゆえ観点は到着順に
      // stage2 へ流れる = 共有カウンタ先着順 admission だと admit 集合が解決順で変わる(非決定)。観点別固定枠
      // なら反転しても admit 集合は同一 — その決定論を behavioral に駆動するための人工遅延。
      if (REVIEW_ORDER === 'reverse') {
        const i = reviewSeq++
        return new Promise((r) => setTimeout(() => r(res), (8 - i) * 5))
      }
      return Promise.resolve(res)
    }
    if (label.startsWith('verify:')) return Promise.resolve({ refuted: !!byRound(VERIFY_REFUTED_BY_ROUND, label, VERIFY_REFUTED), confidence: 'high', reasoning: 'stub' })
    if (label.startsWith('autofix')) {
      return Promise.resolve({ applied: ['stub fix'], selfTestRan: true, selfTestPassed: FIX_SELFTEST_PASSED, amended: FIX_SELFTEST_PASSED, summary: FIX_SUMMARY, newDiff: SNAPSHOT })
    }
    return Promise.resolve(null)
  }

  const stubs = {
    agent: agentStub,
    parallel: makeParallel(),
    pipeline: makePipeline(),
    log: (m) => logs.push(String(m)),
    phase: () => {},
    args: wfArgs,
    // (sc-k33c) budget stub: total は CQ_BUDGET_TOTAL(未設定=null=実機の既定)。spent() は「起動した agent 本数 ×
    // CQ_SPEND_PER_AGENT」= token 情報ログ(判定に使わない)の delta を決定論的に駆動する。
    budget: {
      total: BUDGET_TOTAL,
      spent: () => calls.length * SPEND_PER_AGENT,
      remaining: () => (BUDGET_TOTAL === null ? Infinity : Math.max(0, BUDGET_TOTAL - calls.length * SPEND_PER_AGENT)),
    },
    workflow: async () => null,
  }

  const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor
  const body = loadStrippedBody()
  // new AsyncFunction が body を compile する=syntax 不正なら here で throw(wrap 後の syntax 検証)。
  const run = new AsyncFunction(...INJECTED, body)
  const result = await run(...INJECTED.map((k) => stubs[k]))

  return { result, calls, logs, agentTypeCalls, promptCalls, effortCalls }
}

// ── 出力: `K <key> <value>` 行(bats が grep で assert)+ 生 JSON ─────────────────
function firstIndex(calls, prefix) {
  for (let i = 0; i < calls.length; i++) if (calls[i].startsWith(prefix)) return i
  return -1
}

function printResult(result, calls, logs, agentTypeCalls, promptCalls, effortCalls) {
  const K = (k, v) => console.log(`K ${k} ${v}`)
  const b = result.selfTestBaseline || {}
  const f = result.selfTestFinal || {}
  K('selfTestBaseline.present', result.selfTestBaseline !== undefined)
  K('selfTestBaseline.ran', b.ran)
  K('selfTestBaseline.skipped', b.skipped === true)
  K('selfTestBaseline.passed', b.passed)
  K('selfTestBaseline.hasRawLog', typeof b.rawLog === 'string' && b.rawLog.length > 0)
  K('selfTestBaseline.rawLog_len', typeof b.rawLog === 'string' ? b.rawLog.length : -1)
  K('selfTestBaseline.error', b.error === true)
  K('selfTestFinal.present', result.selfTestFinal !== undefined)
  K('selfTestFinal.ran', f.ran)
  K('selfTestFinal.skipped', f.skipped === true)
  K('selfTestFinal.passed', f.passed)
  K('selfTestFinal.hasRawLog', typeof f.rawLog === 'string' && f.rawLog.length > 0)
  K('selfTestFinal.error', f.error === true)
  K('converged', result.converged === true)
  K('escalate', result.escalate === true)
  K('autoFix', result.autoFix === true)
  K('taskType', result.taskType)
  K('rounds', result.rounds)
  const selftestCalls = calls.filter((c) => c.startsWith('selftest:')).length
  K('selftestAgentCalls', selftestCalls)
  const bi = firstIndex(calls, 'selftest:baseline')
  const fi = firstIndex(calls, 'selftest:final')
  K('baselineBeforeFinal', bi >= 0 && fi >= 0 ? bi < fi : 'na')
  // baseline は implement/review より前(実装前=regression 起点)であることも順序で確認。
  const impl = firstIndex(calls, 'implement')
  const rev = firstIndex(calls, 'review:')
  K('baselineBeforeReview', bi >= 0 && rev >= 0 ? bi < rev : 'na')
  K('baselineBeforeImplement', bi >= 0 && impl >= 0 ? bi < impl : 'na')
  // gate は空白を含むので substring 判定用に prefix だけ出す。
  const gate = String(result.gate || '')
  K('gatePrefix', gate.split(':')[0])
  // (sc-xyw) roAgent fallback の監査軸。
  // roFallbackActive: 全 return 経路で返り値に載る最終降格状態(acceptance 3)。
  // roFallbackLogCount: [RO-FALLBACK] loud log の回数(fallback シナリオでちょうど 1=降格が後続伝播した証拠)。
  // agentTypeCallCount: agentType 付きで呼ばれた総数(fallback シナリオで 1=初回のみ agentType 付き→以降降格伝播で 0)。
  // reviewVerifyCalls: review:/verify: 段が実際に走った数(fallback 後も review/verify 経路が生きている証拠)。
  K('roFallbackActive', result.roFallbackActive === true)
  const roFbLogCount = (logs || []).filter((l) => String(l).includes('[RO-FALLBACK]')).length
  K('roFallbackLogCount', roFbLogCount)
  K('agentTypeCallCount', (agentTypeCalls || []).length)
  // (sc-xyw errata) roDisciplineCallCount: prompt に RO_DISCIPLINE 前置マーカーが付いた呼出しの総数。
  // fallback シナリオで >0(降格後の read-only 段が read-only 規律を prompt で代替)・正常時で 0(前置しない)。
  // この前置が消えても従来の log/agentType 系 assert は全 green ゆえ、silent fail-open 退行を捕える専用軸。
  const roDisciplineCallCount = (promptCalls || []).filter((p) => p && p.hasDiscipline).length
  K('roDisciplineCallCount', roDisciplineCallCount)
  // (sc-mbcm) prompt 内容の汎用 grep 軸: env CQ_PROMPT_GREP を含む prompt を持った呼出しの数と label prefix。
  // contextFile の ctxBlock 注入(classify/plan/implement/review/fix に付き verify/snapshot に付かない)等、
  // prompt-level の配線を behavioral に assert する(未設定時は何も出さない=既存 assert に影響ゼロ)。
  const pg = process.env.CQ_PROMPT_GREP || ''
  if (pg) {
    const hits = (promptCalls || []).filter((p) => p && typeof p.prompt === 'string' && p.prompt.includes(pg))
    K('promptGrepCount', hits.length)
    K('promptGrepLabels', Array.from(new Set(hits.map((h) => String(h.label).split(' ')[0]))).sort().join(','))
  }
  const rvCalls = calls.filter((c) => c.startsWith('review:') || c.startsWith('verify:')).length
  K('reviewVerifyCalls', rvCalls)
  // (sc-dc9) effort pin の behavioral 検証: 全 agent 呼出しに opts.effort が届いたか + その distinct 値。
  // effortAgentCalls: effort を記録した呼出し総数(= 全 agent 呼出し)。
  // effortAllPinned: すべての agent 呼出しで effort が defined(undefined が 1 つも無い=全箇所 pin の証拠)。
  // effortDistinct: 実際に届いた effort の distinct 値(既定なら 'high' のみ・args.effort 指定ならその値)。
  const ec = effortCalls || []
  K('effortAgentCalls', ec.length)
  K('effortAllPinned', ec.length > 0 && ec.every((e) => e && e.effort !== undefined))
  K('effortDistinct', Array.from(new Set(ec.map((e) => String(e && e.effort)))).sort().join(','))
  // (sc-94z) per-stage effort の behavioral 検証: 各段の agent 呼出しに届いた opts.effort を label prefix 別に読む。
  // guard 段(review/verify/fix)が cell effort の一括下げから独立に high を保つか等を段ごとに pin する。
  // 該当段が走らなかった run(clean review で fix なし・doPlan/doImplement 無しで plan/implement なし)は '<none>'。
  const effortOf = (prefix) => {
    const hit = ec.find((e) => e && typeof e.label === 'string' && e.label.startsWith(prefix))
    return hit ? String(hit.effort) : '<none>'
  }
  K('effortStage.classify', effortOf('classify'))
  K('effortStage.selftest', effortOf('selftest:'))
  K('effortStage.snapshot', effortOf('snapshot'))
  K('effortStage.plan', effortOf('plan'))
  K('effortStage.implement', effortOf('implement'))
  K('effortStage.review', effortOf('review:'))
  K('effortStage.verify', effortOf('verify:'))
  K('effortStage.fix', effortOf('autofix'))
  // (sc-94z) result.effort は per-stage 要約 object へ変わった(旧: 単一 string)。各フィールドを個別に出す。
  const re = result.effort && typeof result.effort === 'object' ? result.effort : {}
  K('resultEffort.cell', re.cell)
  K('resultEffort.review', re.review)
  K('resultEffort.verify', re.verify)
  K('resultEffort.fix', re.fix)
  K('resultEffort.classify', re.classify)
  K('resultEffort.selfTest', re.selfTest)
  K('resultEffort.snapshot', re.snapshot)
  // (sc-dc9) allowlist 外 args.effort → 既定 high へ fail-safe した際、warn log が実際に発火したか(behavioral)。
  // logs は既定では stdout に dump しないため、この behavioral K 行で fail-safe の可視化(silent に倒さない)を検証する。
  K('effortFailSafeWarned', (logs || []).some((l) => String(l).includes('許可外')))
  // (sc-2wv) guard 段 knob(reviewEffort/verifyEffort)を floor(high)未満で渡した際、WF が fail-safe で high へ
  // 引き上げ warn したか(behavioral)。floor-clamp は '許可外'(allowlist 外)とは別経路(allowlist 内だが下げ拒否)
  // ゆえ専用マーカー '下限フロア' で弁別する。これが消える(silent に下げる)退行を behavioral に捕える。
  K('effortFloorClamped', (logs || []).some((l) => String(l).includes('下限フロア')))
  // ── (sc-k33c) cap の behavioral 観測軸 ───────────────────────────────────────
  // callSeq: agent 呼出し label の | 連結。K2'(後方互換)の golden 比較と K3(本数 assert)の一次データ。
  // label には round 番号が入る(例 'review:correctness r1')ので、呼出し列の同一性がそのまま比較できる。
  K('callSeq', calls.join('|'))
  K('agentCallTotal', calls.length)
  const cr = result.capReport && typeof result.capReport === 'object' ? result.capReport : {}
  const cd = Array.isArray(result.capDropped) ? result.capDropped : []
  K('capExceeded', result.capExceeded === true)
  K('capReason', String(cr.reason === undefined ? '<none>' : cr.reason || '<empty>'))
  K('capLimit', cr.limit)
  K('capUnit', cr.unit)
  K('capSpentEstimate', cr.spentEstimate)
  K('capDroppedAgents', cr.droppedAgents)
  K('capDroppedBlocking', cr.droppedBlocking)
  K('capHistoryCount', cr.historyCount)
  // (sc-k33c errata) self-test 段(情報ログ専用=B4)で捕捉した cap 例外の件数。terminal/round gate を駆動せず
  // ここだけに載る = 「可視化は残しつつ converged/escalate を反転させない」の behavioral 観測軸。
  K('capSelfTestExceptions', Array.isArray(cr.selfTestExceptions) ? cr.selfTestExceptions.length : -1)
  K('capStagesCount', Array.isArray(cr.stages) ? cr.stages.length : -1)
  K('capBudgetTotal', cr.budgetTotal === null ? 'null' : cr.budgetTotal)
  K('capTokenDelta', cr.tokenDelta === null ? 'null' : cr.tokenDelta)
  K('capDroppedCount', cd.length)
  K('capDroppedReasons', Array.from(new Set(cd.map((d) => String(d && d.reason)))).sort().join(','))
  // capDroppedTitles: 落とした対象の決定論 pin(順序に依らない集合比較用に sort する)。
  K('capDroppedTitles', cd.map((d) => String(d && d.title)).sort().join(';'))
  // verifyLabels: 実際に verify を起動した label の集合(sort 済)= stage1 の解決順を入れ替えても同一であること
  // (K1c の決定論 pin)を集合比較する。verifyByDim: 観点別の verify 本数(観点単位 top-K の behavioral 面)。
  const verifyCalls = calls.filter((c) => c.startsWith('verify:'))
  K('verifyLabels', verifyCalls.slice().sort().join(';'))
  K('verifyCallCount', verifyCalls.length)
  const byDim = {}
  for (const c of verifyCalls) {
    const dim = c.split(':')[1] || '?'
    byDim[dim] = (byDim[dim] || 0) + 1
  }
  K('verifyByDim', Object.keys(byDim).sort().map((k) => `${k}=${byDim[k]}`).join(','))
  K('reviewCallCount', calls.filter((c) => c.startsWith('review:')).length)
  K('unverifiedCount', Array.isArray(result.unverified) ? result.unverified.length : -1)
  // unverifiedTitles: capDropped[] と **同じ finding が二重計上されていない** ことを集合で比較するための軸。
  K('unverifiedTitles', Array.isArray(result.unverified) ? Array.from(new Set(result.unverified.map((f) => String(f && f.title)))).sort().join(';') : '')
  K('blockingCount', Array.isArray(result.blocking) ? result.blocking.length : -1)
  K('minorCount', Array.isArray(result.minor) ? result.minor.length : -1)
  K('gateHasCapNote', gate.includes('※cap 発火'))
  console.log(`ESCALATE_REASON ${String(result.escalateReason || '')}`)
  console.log(`RESULT ${JSON.stringify(result)}`)
}

// ── entrypoint ───────────────────────────────────────────────────────────────
const mode = process.argv[2] || 'run'
if (mode === 'emit-wrapped') {
  process.stdout.write(emitWrapped())
} else if (mode === 'run') {
  runWorkflow()
    .then(({ result, calls, logs, agentTypeCalls, promptCalls, effortCalls }) => {
      printResult(result, calls, logs, agentTypeCalls, promptCalls, effortCalls)
    })
    .catch((e) => {
      console.error(`DRIVER_ERROR: ${e && e.stack ? e.stack : e}`)
      // (sc-pfn4) throw 経路の観測面: 「agent が 1 体も起動していない」(=fail-fast より前に仕事を始めていない)
      // を bats が機械 assert できるようにする。成功経路の stdout(K 行 / RESULT 行)には一切足さない。
      console.error(`DRIVER_AGENT_CALLS ${collected.calls.length}`)
      console.error(`DRIVER_CALLSEQ ${collected.calls.join('|')}`)
      process.exit(1)
    })
} else {
  console.error(`unknown mode: ${mode}`)
  process.exit(2)
}
